Wrapped library into symfony bundle
4xxi/rest-request-errors pull request #5
Opened 2020-04-28 15:00 UTC by dbezmelnitsyn

2020-04-28 16:40 UTC, aburov-4xxi commented on src/EventListener/ExceptionResponseListener.php
> +        $response = new JsonResponse();
можно инициализировать ниже

2020-04-28 16:45 UTC, aburov-4xxi commented on src/EventListener/ExceptionResponseListener.php
> +        $response->setJson($this->serializer->serialize($exception, 'json'));
можно сделать декоратор (интерфейс) для $this->serializer->serialize который можно настраивать в настройках бандла, чтобы получать любые форматы ошибок, например если нужен вот такой формат ```{"code": 400, "errors" => {}}```

2020-04-29 08:17 UTC, aburov-dev approved these changes

2020-04-29 08:24 UTC, artem328 requested changes

2020-04-29 08:24 UTC, artem328 commented on src/Serializer/InvalidRequestExceptionNormalizer.php
> +        $serializer = new Serializer([new ObjectNormalizer()]);
Не понятно зачем инициализировать сериалайзер, чтоб использововать метод normalize. Я думаю лучше имплементировать интерфейс NormalizerAwareInterface и нормалайзером который передается аргуметом в setNormalizer нормализовывать вьюху.

2020-04-29 08:24 UTC, artem328 commented on tests/ExceptionResponseListenerTest.php
> +    private $serializator;
serializer

2020-04-29 09:20 UTC, artem328 approved these changes

2020-04-29 09:24 UTC, merged